# Generated by Django 5.2.5 on 2025-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='customer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
