# Generated by Django 5.2.5 on 2025-09-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_total_sales_product_total_sales_amount'),
    ]

    operations = [
    ]
