# Generated by Django 5.2.5 on 2025-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20250902_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='instamojo_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='instamojo_payment_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
